name: Gcm
title: Gcm
description: Google Guice component management System!
url: https://gcm.incubator.edurt.io
disqus_shortname: edurtio
baseurl:

active_sibling:
main_url:
permalink: pretty

lang: en_NZ
logo: /siteicon.png

plugins:
  - jekyll-data
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

collections_dir: collections
collections:
  databases_docs:
    title: DataBases
    permalink: /databases/:path/
    output: true
    boost: 8
  general_docs:
    title: General
    permalink: /general/:path/
    output: true
    boost: 8
  bigdata_docs:
    title: BigData
    permalink: /bigdata/:path/
    output: true
    boost: 8
  sections:
    title: Sections
    permalink: /:path/
    output: false

defaults:
  - scope:
      path: ""
    values:
      hide_cta: true
      layout: doc
      search_result_highlighting_selector: article.content
      _options:
        content:
          format: p h2 h3
          bold: true
          link: true
          italic: true
          removeformat: true
          numberedlist: true
          bulletedlist: true
          code: true
          table: true
          outdent: true
          indent: true
          image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      search_result_highlighting_selector: div.post
      hide_disqus: true
      uploads_dir: /images/change-log/:title
      _comments:
        type: Marks the impact of this release
      _options:
        content:
          format: p h2 h3
          bold: true
          link: true
          italic: true
          removeformat: true
          numberedlist: true
          bulletedlist: true
          code: true
          table: true
          outdent: true
          indent: true
          image: true
